#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TokenType {
    LeftParen,
    RightParen,
    LeftCurlyBrace,
    RightCurlyBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Bang,
    BangEqual,
    Equal,
    EqualEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    FatArrow,
    LambdaStart,
    And,
    Or,
    Else,
    Fn,
    For,
    If,
    Null,
    Return,
    Continue,
    Break,
    True,
    False,
    Let,
    Mut,
    While,

    StringLiteral,
    IntegerLiteral,
    FloatLiteral,
    Identifier,
}

pub struct Token {
    pub token_type: TokenType,
    pub id: SpanIdentifier,
    pub literal_value: Option<String>,
}

pub struct SpanIdentifier {
    pub filename: String,
    pub line: usize,
    pub span: (usize, usize),
    pub value: String,
}
